name: Edit Files

on: push
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Edit Files
      uses: TaiStudio/action-edit-YML@main
      with:
        type: 'single'
        files: "./example/lastest.yml"
        elementSTR: "['files'][0]['url']"
        replace: "-"
        replaceFor: "."
